In [ ]:
# myHW-module4-python-a2-bc-2213031903.ipynb   Numpy

In [2]:
#task1:
import numpy as np
np.random.randint(2,10,9).reshape(3,3)

array([[8, 5, 9],
       [7, 5, 5],
       [2, 9, 4]])

In [5]:
#task2:
a001 = np.arange(10,50,5)
a001

array([10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
a002=a001.astype(float)
a002

array([10., 15., 20., 25., 30., 35., 40., 45.])

In [11]:
print(a001)

[10 15 20 25 30 35 40 45]


In [16]:
a001=[10, 15, 20, 25, 30, 35, 40, 45]
a004=[50,55,60,65,70,75]
a008=np.append(a001,a004)
a008

#arr3 = np.append(arr1, arr2)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [20]:
#task3:

a001=[10, 15, 20, 25, 30, 35, 40, 45]

a007=[11,12,13,14,15,16,17,18]
sumArray=np.add(a001,a007)  
sumArray  

array([21, 27, 33, 39, 45, 51, 57, 63])

In [23]:
#task4:

array1 = np.random.randint(10,90,9).reshape(3,3)

array1

array([[75, 27, 41],
       [48, 13, 36],
       [70, 65, 79]])

In [24]:

array1[0]

array([75, 27, 41])

In [25]:
array1[2][2]

79