In [2]:
#myHW-module4-python-case-study-1-bc-2213031903

#numpy assignment
#task1: create a function that takes dimentions as tuple and returns numpy array:

import numpy as np
    
np.random.random((3,3))

array([[0.30951641, 0.32466329, 0.00446644],
       [0.45571807, 0.22903111, 0.27714722],
       [0.75319215, 0.91409811, 0.00347278]])

In [4]:
aa=np.random.random((3,3))
aa

array([[0.85675728, 0.69738065, 0.06970843],
       [0.09148644, 0.07396525, 0.83635354],
       [0.84997799, 0.16394351, 0.8938456 ]])

In [5]:
bb=np.random.random((3,3))
bb

array([[0.00652382, 0.56436336, 0.35973624],
       [0.71818498, 0.29171514, 0.59780866],
       [0.63996878, 0.21456717, 0.35522884]])

In [6]:
#task2:

aa+bb

array([[0.8632811 , 1.26174401, 0.42944467],
       [0.80967143, 0.36568039, 1.4341622 ],
       [1.48994677, 0.37851068, 1.24907444]])

In [10]:
#task3:

aaa=np.array([[0,5,10],[10,15,20],[20,25,30],[30,35,40]])
bbb=np.array([0,1,2])

In [11]:
aaa

array([[ 0,  5, 10],
       [10, 15, 20],
       [20, 25, 30],
       [30, 35, 40]])

In [15]:
aaa[0:2]     #takes first 2 rows

array([[ 0,  5, 10],
       [10, 15, 20]])

In [16]:
aaa[0:2,0:2]   #takes first 2 rows and first 2 columns

array([[ 0,  5],
       [10, 15]])