In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
#homework - python - module 9, case study 1: 
#Movie Recommender System with SVD algorithm (singular value decomposition):

#1.a. load moves and ratings datasets
#1.b.find unique number of users and movies in ratings dataset
#1.c. create a rating matrix in rating dataset and store it in Ratings.
#1.d. load ratings dataset as SVD dataset object and compute 3D-fold-cross-validation using the SVD object.
#1.e. find all the movies rated as 5 stars by user id 5 and store it in ratings_1 dataframe
#1.f. create shallow copy of movies dataset and store the result in user_5
#1.g. train recommender system using SVD object and predict the ratings for user id 5
#1.h.print the top 10 movie recommendations for the user id 5


In [3]:
movie = pd.read_csv('movies.csv')
movie.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [49]:
movie.shape

(27278, 3)

In [50]:
movie.describe()

movieId
count   27278.000000
mean    59855.480570
std     44429.314697
min         1.000000
25%      6931.250000
50%     68068.000000
75%    100293.250000
max    131262.000000

In [51]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  27278 non-null  int64 
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB


In [4]:
rating = pd.read_csv('ratings.csv')
rating.head()

userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [53]:
rating.shape

(1048575, 4)

In [54]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   userId     1048575 non-null  int64  
 1   movieId    1048575 non-null  int64  
 2   rating     1048575 non-null  float64
 3   timestamp  1048575 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 32.0 MB


In [4]:
#1.b.find unique number of users and movies in ratings dataset

rating.userId.unique()

array([   1,    2,    3, ..., 7118, 7119, 7120])

In [56]:
len(rating.userId.unique())

#so we see 7120 unique users

7120

In [57]:
len(rating.movieId.unique())

# there are 14026 unique movies

14026

In [6]:
#1.c. create a rating matrix in rating dataset and store it in Ratings:
#1.c. create a rating matrix in rating dataset and store it in Ratings:

Ratings_df=movie[rating['rating']==5]
Ratings_df.head()

<ipython-input-6-91865a42459a>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Ratings_df=movie[rating['rating']==5]


movieId                          title                           genres
131      133               Nueba Yol (1995)                     Comedy|Drama
142      144  Brothers McMullen, The (1995)                           Comedy
158      160                   Congo (1995)  Action|Adventure|Mystery|Sci-Fi
170      172         Johnny Mnemonic (1995)           Action|Sci-Fi|Thriller
176      178    Love & Human Remains (1993)                     Comedy|Drama

In [ ]:
#1.d. load ratings dataset as SVD dataset object and compute 3D-fold-cross-validation using the SVD object.

In [7]:
dfm = movie.merge(rating, how="left", on="movieId")
dfm

movieId                          title  \
0              1               Toy Story (1995)   
1              1               Toy Story (1995)   
2              1               Toy Story (1995)   
3              1               Toy Story (1995)   
4              1               Toy Story (1995)   
...          ...                            ...   
1061822   131254   Kein Bund für's Leben (2007)   
1061823   131256  Feuer, Eis & Dosenbier (2002)   
1061824   131258             The Pirates (2014)   
1061825   131260            Rentun Ruusu (2001)   
1061826   131262               Innocence (2014)   

                                              genres  userId  rating  \
0        Adventure|Animation|Children|Comedy|Fantasy     3.0     4.0   
1        Adventure|Animation|Children|Comedy|Fantasy     6.0     5.0   
2        Adventure|Animation|Children|Comedy|Fantasy     8.0     4.0   
3        Adventure|Animation|Children|Comedy|Fantasy    10.0     4.0   
4        Adventure|Animation|Children|Comedy|Fantasy    11.0     4.5   
...                                              ...     ...     ...   
1061822                                       Comedy     NaN     NaN   
1061823                                       Comedy     NaN     NaN   
1061824                                    Adventure     NaN     NaN   
1061825                           (no genres listed)     NaN     NaN   
1061826                     Adventure|Fantasy|Horror     NaN     NaN   

            timestamp  
0        9.449194e+08  
1        8.582755e+08  
2        8.339819e+08  
3        9.434979e+08  
4        1.230859e+09  
...               ...  
1061822           NaN  
1061823           NaN  
1061824           NaN  
1061825           NaN  
1061826           NaN  

[1061827 rows x 6 columns]

In [ ]:
#movies = pd.read_table('../../dataset/ml-1m/movies.dat', 
 #                      sep='::', header=None, engine='python', encoding='utf-8').to_numpy()

In [10]:
data = pd.io.parsers.read_csv('ml-1m/ratings.dat', 
    names=['user_id', 'movie_id', 'rating', 'time'],
    engine='python', encoding='ISO-8859-1', delimiter='::')
movie_data = pd.io.parsers.read_csv('ml-1m/movies.dat',
    names=['movie_id', 'title', 'genre'],
    engine='python', encoding='ISO-8859-1', delimiter='::')


In [56]:
data

user_id  movie_id  rating       time
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
...          ...       ...     ...        ...
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [11]:
#Creating the ratings matrix of shape (m×u) with rows as movies and columns as users

ratings_mat = np.ndarray(
    shape=(np.max(data.movie_id.values), np.max(data.user_id.values)),
    dtype=np.uint8)
ratings_mat[data.movie_id.values-1, data.user_id.values-1] = data.rating.values

In [13]:
#ratings_mat

In [14]:
#Normalising ratings_matrix:

normalised_mat = ratings_mat - np.asarray([(np.mean(ratings_mat, 1))]).T

In [15]:
#computing SVD:

A = normalised_mat.T / np.sqrt(ratings_mat.shape[0] - 1)
U, S, V = np.linalg.svd(A)

In [16]:
# Calculating cosine similarity sorting by most similar and return the top N:

def top_cosine_similarity(data, movie_id, top_n=10):
    index = movie_id - 1 # Movie id starts from 1
    movie_row = data[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(movie_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    return sort_indexes[:top_n]

# Helper function to print top N similar movies
def print_similar_movies(movie_data, movie_id, top_indexes):
    print('Recommendations for {0}: \n'.format(
    movie_data[movie_data.movie_id == movie_id].title.values[0]))
    for id in top_indexes + 1:
        print(movie_data[movie_data.movie_id == id].title.values[0])

In [17]:
#Select k principal components to represent the movies, a movie_id to find recommendations 
#and print the top_n results.


k = 50
movie_id = 1 # Grab an id from movies.dat
top_n = 10

sliced = V.T[:, :k] # representative data
indexes = top_cosine_similarity(sliced, movie_id, top_n)
print_similar_movies(movie_data, movie_id, indexes)


#We can change k and use different number of principal components to represent our dataset

Recommendations for Toy Story (1995): 

Toy Story (1995)
Georgia (1995)
Lamerica (1994)
Catwalk (1995)
400 Blows, The (Les Quatre cents coups) (1959)
Whatever It Takes (2000)
Chushingura (1962)
Way of the Gun, The (2000)
Grandfather, The (El Abuelo) (1998)
Teaching Mrs. Tingle (1999)


In [ ]:
#1.e. find all the movies rated as 5 stars by user id 5 and store it in ratings_1 dataframe

In [8]:
user5_5stars=df[(df_ratings['userId']==5) & (df_ratings['rating']==5)]
user5_5stars.head()

<ipython-input-8-bf498e1348f5>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  user5_5stars=df[(df_ratings['userId']==5) & (df_ratings['rating']==5)]


movieId                   title  \
452      456            Fresh (1994)   
455      459     Getaway, The (1994)   
459      463    Guilty as Sin (1993)   
460      464      Hard Target (1993)   
463      467  Live Nude Girls (1995)   

                                            genres  
452                           Crime|Drama|Thriller  
455  Action|Adventure|Crime|Drama|Romance|Thriller  
459                           Crime|Drama|Thriller  
460                Action|Adventure|Crime|Thriller  
463                                         Comedy

In [10]:
user5_5stars.shape

(38, 3)

In [9]:
user5_5stars['movieId'].unique()

array([456, 459, 463, 464, 467, 470, 472, 474, 477, 478, 479, 480, 481,
       485, 486, 489, 491, 492, 493, 495, 496, 500, 502, 503, 504, 506,
       507, 508, 509, 512, 513, 514, 515, 516, 517, 518, 519, 520])

In [25]:
len(user5_5stars['movieId'].unique())

#we see that 38 unique movies are rated by user_5 as 5_starts_movies

38

In [28]:
Ratings_df = df[df_ratings['rating']==5]
Ratings_df.head()

<ipython-input-28-9700fa7ea9e0>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Ratings_df = df[df_ratings['rating']==5]


movieId                          title                           genres
131      133               Nueba Yol (1995)                     Comedy|Drama
142      144  Brothers McMullen, The (1995)                           Comedy
158      160                   Congo (1995)  Action|Adventure|Mystery|Sci-Fi
170      172         Johnny Mnemonic (1995)           Action|Sci-Fi|Thriller
176      178    Love & Human Remains (1993)                     Comedy|Drama

In [41]:
df_r_u5 = df_ratings[df_ratings['userId'] == 5]

df_r_u5

userId  movieId  rating  timestamp
451       5        2     3.0  851527569
452       5       11     5.0  851527751
453       5       17     3.0  851526935
454       5       60     3.0  851617589
455       5       62     5.0  851526935
..      ...      ...     ...        ...
512       5     1196     5.0  851617674
513       5     1198     5.0  851617674
514       5     1210     5.0  851617674
515       5     1291     5.0  851617728
516       5     1393     5.0  851527231

[66 rows x 4 columns]

In [12]:
df_ratings.rating.unique()

array([3.5, 4. , 3. , 4.5, 5. , 2. , 1. , 2.5, 0.5, 1.5])

In [13]:
df_ratings.rating.value_counts()

4.0    295135
3.0    226202
5.0    152562
3.5    112926
4.5     79848
2.0     74706
2.5     44791
1.0     35144
1.5     14029
0.5     13232
Name: rating, dtype: int64

In [14]:
ratings_1 = df[df_ratings['rating']==5]
ratings_1

<ipython-input-14-d7d1af1c483c>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ratings_1 = df[df_ratings['rating']==5]


movieId                              title  \
131        133                   Nueba Yol (1995)   
142        144      Brothers McMullen, The (1995)   
158        160                       Congo (1995)   
170        172             Johnny Mnemonic (1995)   
176        178        Love & Human Remains (1993)   
...        ...                                ...   
27255   131160  Oscar and the Lady in Pink (2009)   
27265   131231                     Standby (2014)   
27268   131241           Ants in the Pants (2000)   
27271   131250              No More School (2000)   
27273   131254       Kein Bund für's Leben (2007)   

                                genres  
131                       Comedy|Drama  
142                             Comedy  
158    Action|Adventure|Mystery|Sci-Fi  
170             Action|Sci-Fi|Thriller  
176                       Comedy|Drama  
...                                ...  
27255                            Drama  
27265                   Comedy|Romance  
27268                   Comedy|Romance  
27271                           Comedy  
27273                           Comedy  

[4189 rows x 3 columns]

In [15]:
ratings_1.shape

(4189, 3)

In [ ]:
#1.f. create shallow copy of movies dataset and store the result in user_5:

#lets make the dataset of all movies rated by user_5 
#as we see below it is 66 movies.

In [18]:
user5_all_rated_movies=df[(df_ratings['userId']==5)]
user5_all_rated_movies.head()

<ipython-input-18-2212af84fefc>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  user5_all_rated_movies=df[(df_ratings['userId']==5)]


movieId                                title  \
451      455                    Free Willy (1993)   
452      456                         Fresh (1994)   
453      457                 Fugitive, The (1993)   
454      458  Geronimo: An American Legend (1993)   
455      459                  Getaway, The (1994)   

                                            genres  
451                       Adventure|Children|Drama  
452                           Crime|Drama|Thriller  
453                                       Thriller  
454                                  Drama|Western  
455  Action|Adventure|Crime|Drama|Romance|Thriller

In [19]:
user5_all_rated_movies.shape

(66, 3)

In [21]:
len(user5_all_rated_movies.movieId.unique())

66

In [ ]:
#1.g. train recommender system using SVD object and predict the ratings for user id 5

In [ ]:
data = pd.io.parsers.read_csv('ml-1m/ratings.dat', 
    names=['user_id', 'movie_id', 'rating', 'time'],
    engine='python', encoding='ISO-8859-1', delimiter='::')
movie_data = pd.io.parsers.read_csv('ml-1m/movies.dat',
    names=['movie_id', 'title', 'genre'],
    engine='python', encoding='ISO-8859-1', delimiter='::')

In [57]:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings_train = data[0:800000]
ratings_test = data[800001:1000000]
ratings_train.shape, ratings_test.shape

((800000, 4), (199999, 4))

In [58]:
ratings_train

user_id  movie_id  rating       time
0             1      1193       5  978300760
1             1       661       3  978302109
2             1       914       3  978301968
3             1      3408       4  978300275
4             1      2355       5  978824291
...         ...       ...     ...        ...
799995     4794       904       5  962995909
799996     4794       908       5  962996028
799997     4794       913       5  962995617
799998     4794       919       5  962996139
799999     4794      3072       5  963030385

[800000 rows x 4 columns]

In [59]:
n_users = ratings_train.user_id.unique().shape[0]
n_items = ratings_train.movie_id.unique().shape[0]

In [61]:
data_matrix = np.zeros((n_users, n_items))
#for line in ratings_train.itertuples():
    #data_matrix[line[1]-1, line[2]-1] = line[3]

In [63]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [35]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [64]:
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

In [65]:
user_prediction

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [76]:
predict(data_matrix, user_similarity, type='user')

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
def movie_rater(movie_df,num, genre=None):
    userID = 5
    rating_list = []
    while num > 0:
        if genre:
            movie = movie_df[movie_df['genres'].str.contains(genre)].sample(1)
        else:
            movie = movie_df.sample(1)
        print(movie)
        rating = input('How do you rate this movie on a scale of 1-5, press n if you have not seen :\n')
        if rating == 'n':
            continue
        else:
            rating_one_movie = {'userId':userID,'movieId':movie['movieId'].values[0],'rating':rating}
            rating_list.append(rating_one_movie) 
            num -= 1
    return rating_list

In [ ]:
user_rating = movie_rater(df_movies,4,'Comedy')

In [ ]:
user_rating

[{'userId': 5, 'movieId': 55245, 'rating': '5'},
 {'userId': 5, 'movieId': 2491, 'rating': '4'},
 {'userId': 5, 'movieId': 4718, 'rating': '4'},
 {'userId': 5, 'movieId': 5990, 'rating': '3'}]

In [ ]:
#1.h.print the top 10 movie recommendations for the user id 5

In [22]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import scale


def predict(l):
    # finds the userIds corresponding to the top 5 similarities
    # calculate the prediction according to the formula
    return (df[l.index] * l).sum(axis=1) / l.sum()


# use userID as columns for convinience when interpretering the forumla
df = pd.read_csv('ratings.csv').pivot(columns='userId',
                                                index='movieId',
                                                values='rating')

similarity = pd.DataFrame(cosine_similarity(
    scale(df.T.fillna(-1000))),
    index=df.columns,
    columns=df.columns)
# iterate each column (userID),
# for each userID find the highest five similarities
# and use to calculate the prediction for that user,
# use fillna so that original ratings dont change

res = df.apply(lambda col: ' '.join('{}'.format(mid) for mid in col.fillna(
    predict(similarity[col.name].nlargest(6).iloc[1:])).nlargest(10).index))
print(res)

userId
1       4993 5952 7153 8507 1196 1198 8636 151 223 253
2              62 70 260 266 480 541 589 924 1196 1210
3               50 175 223 260 316 318 329 457 480 490
4               454 733 457 10 350 356 368 370 377 431
5                11 62 141 150 260 318 364 368 377 380
                             ...                      
7116      58 260 318 589 1073 1136 1196 1197 1210 1246
7117                   6 11 21 23 47 50 95 104 145 161
7118    593 608 908 1079 1193 1230 1234 1235 1238 1244
7119               1 17 32 110 266 318 356 364 457 474
7120                 21 34 110 141 151 168 260 1 17 48
Length: 7120, dtype: object


In [24]:
#1.h.Here - printed the top 10 movie recommendations for the user id 5
print('Here - printed the top 10 movie recommendations for the user_id_5: ')
res.iloc[4]

Here - printed the top 10 movie recommendations for the user_id_5: 


'11 62 141 150 260 318 364 368 377 380'