In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
#homework - python - module 9, case study 1: 
#Movie Recommender System with SVD algorithm (singular value decomposition):

#1.a. load moves and ratings datasets
#1.b.find unique number of users and movies in ratings dataset
#1.c. create a rating matrix in rating dataset and store it in Ratings.
#1.d. load ratings dataset as SVD dataset object and compute 3D-fold-cross-validation using the SVD object.
#1.e. find all the movies rated as 5 stars by user id 5 and store it in ratings_1 dataframe
#1.f. create shallow copy of movies dataset and store the result in user_5
#1.g. train recommender system using SVD object and predict the ratings for user id 5
#1.h.print the top 10 movie recommendations for the user id 5


In [2]:
movie = pd.read_csv('movies.csv')
movie.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [49]:
movie.shape

(27278, 3)

In [50]:
movie.describe()

movieId
count   27278.000000
mean    59855.480570
std     44429.314697
min         1.000000
25%      6931.250000
50%     68068.000000
75%    100293.250000
max    131262.000000

In [51]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  27278 non-null  int64 
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB


In [3]:
rating = pd.read_csv('ratings.csv')
rating.head()

userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [53]:
rating.shape

(1048575, 4)

In [54]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   userId     1048575 non-null  int64  
 1   movieId    1048575 non-null  int64  
 2   rating     1048575 non-null  float64
 3   timestamp  1048575 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 32.0 MB


In [4]:
#1.b.find unique number of users and movies in ratings dataset

rating.userId.unique()

array([   1,    2,    3, ..., 7118, 7119, 7120])

In [56]:
len(rating.userId.unique())

#so we see 7120 unique users

7120

In [57]:
len(rating.movieId.unique())

# there are 14026 unique movies

14026

In [5]:
#1.c. create a rating matrix in rating dataset and store it in Ratings:
#1.c. create a rating matrix in rating dataset and store it in Ratings:

Ratings_df=df[rating['rating']==5]
Ratings_df.head()

NameError: name 'df' is not defined

In [ ]:
#1.d. load ratings dataset as SVD dataset object and compute 3D-fold-cross-validation using the SVD object.

In [6]:
dfm = movie.merge(rating, how="left", on="movieId")
dfm

movieId                          title  \
0              1               Toy Story (1995)   
1              1               Toy Story (1995)   
2              1               Toy Story (1995)   
3              1               Toy Story (1995)   
4              1               Toy Story (1995)   
...          ...                            ...   
1061822   131254   Kein Bund für's Leben (2007)   
1061823   131256  Feuer, Eis & Dosenbier (2002)   
1061824   131258             The Pirates (2014)   
1061825   131260            Rentun Ruusu (2001)   
1061826   131262               Innocence (2014)   

                                              genres  userId  rating  \
0        Adventure|Animation|Children|Comedy|Fantasy     3.0     4.0   
1        Adventure|Animation|Children|Comedy|Fantasy     6.0     5.0   
2        Adventure|Animation|Children|Comedy|Fantasy     8.0     4.0   
3        Adventure|Animation|Children|Comedy|Fantasy    10.0     4.0   
4        Adventure|Animation|Children|Comedy|Fantasy    11.0     4.5   
...                                              ...     ...     ...   
1061822                                       Comedy     NaN     NaN   
1061823                                       Comedy     NaN     NaN   
1061824                                    Adventure     NaN     NaN   
1061825                           (no genres listed)     NaN     NaN   
1061826                     Adventure|Fantasy|Horror     NaN     NaN   

            timestamp  
0        9.449194e+08  
1        8.582755e+08  
2        8.339819e+08  
3        9.434979e+08  
4        1.230859e+09  
...               ...  
1061822           NaN  
1061823           NaN  
1061824           NaN  
1061825           NaN  
1061826           NaN  

[1061827 rows x 6 columns]

In [ ]:
#1.e. find all the movies rated as 5 stars by user id 5 and store it in ratings_1 dataframe

In [8]:
user5_5stars=df[(df_ratings['userId']==5) & (df_ratings['rating']==5)]
user5_5stars.head()

<ipython-input-8-bf498e1348f5>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  user5_5stars=df[(df_ratings['userId']==5) & (df_ratings['rating']==5)]


movieId                   title  \
452      456            Fresh (1994)   
455      459     Getaway, The (1994)   
459      463    Guilty as Sin (1993)   
460      464      Hard Target (1993)   
463      467  Live Nude Girls (1995)   

                                            genres  
452                           Crime|Drama|Thriller  
455  Action|Adventure|Crime|Drama|Romance|Thriller  
459                           Crime|Drama|Thriller  
460                Action|Adventure|Crime|Thriller  
463                                         Comedy

In [10]:
user5_5stars.shape

(38, 3)

In [9]:
user5_5stars['movieId'].unique()

array([456, 459, 463, 464, 467, 470, 472, 474, 477, 478, 479, 480, 481,
       485, 486, 489, 491, 492, 493, 495, 496, 500, 502, 503, 504, 506,
       507, 508, 509, 512, 513, 514, 515, 516, 517, 518, 519, 520])

In [25]:
len(user5_5stars['movieId'].unique())

#we see that 38 unique movies are rated by user_5 as 5_starts_movies

38

In [28]:
Ratings_df = df[df_ratings['rating']==5]
Ratings_df.head()

<ipython-input-28-9700fa7ea9e0>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Ratings_df = df[df_ratings['rating']==5]


movieId                          title                           genres
131      133               Nueba Yol (1995)                     Comedy|Drama
142      144  Brothers McMullen, The (1995)                           Comedy
158      160                   Congo (1995)  Action|Adventure|Mystery|Sci-Fi
170      172         Johnny Mnemonic (1995)           Action|Sci-Fi|Thriller
176      178    Love & Human Remains (1993)                     Comedy|Drama

In [41]:
df_r_u5 = df_ratings[df_ratings['userId'] == 5]

df_r_u5

userId  movieId  rating  timestamp
451       5        2     3.0  851527569
452       5       11     5.0  851527751
453       5       17     3.0  851526935
454       5       60     3.0  851617589
455       5       62     5.0  851526935
..      ...      ...     ...        ...
512       5     1196     5.0  851617674
513       5     1198     5.0  851617674
514       5     1210     5.0  851617674
515       5     1291     5.0  851617728
516       5     1393     5.0  851527231

[66 rows x 4 columns]

In [12]:
df_ratings.rating.unique()

array([3.5, 4. , 3. , 4.5, 5. , 2. , 1. , 2.5, 0.5, 1.5])

In [13]:
df_ratings.rating.value_counts()

4.0    295135
3.0    226202
5.0    152562
3.5    112926
4.5     79848
2.0     74706
2.5     44791
1.0     35144
1.5     14029
0.5     13232
Name: rating, dtype: int64

In [14]:
ratings_1 = df[df_ratings['rating']==5]
ratings_1

<ipython-input-14-d7d1af1c483c>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ratings_1 = df[df_ratings['rating']==5]


movieId                              title  \
131        133                   Nueba Yol (1995)   
142        144      Brothers McMullen, The (1995)   
158        160                       Congo (1995)   
170        172             Johnny Mnemonic (1995)   
176        178        Love & Human Remains (1993)   
...        ...                                ...   
27255   131160  Oscar and the Lady in Pink (2009)   
27265   131231                     Standby (2014)   
27268   131241           Ants in the Pants (2000)   
27271   131250              No More School (2000)   
27273   131254       Kein Bund für's Leben (2007)   

                                genres  
131                       Comedy|Drama  
142                             Comedy  
158    Action|Adventure|Mystery|Sci-Fi  
170             Action|Sci-Fi|Thriller  
176                       Comedy|Drama  
...                                ...  
27255                            Drama  
27265                   Comedy|Romance  
27268                   Comedy|Romance  
27271                           Comedy  
27273                           Comedy  

[4189 rows x 3 columns]

In [15]:
ratings_1.shape

(4189, 3)

In [ ]:
#1.f. create shallow copy of movies dataset and store the result in user_5:

#lets make the dataset of al movies rated by user_5 
#as we see below it is 66 movies.

In [18]:
user5_all_rated_movies=df[(df_ratings['userId']==5)]
user5_all_rated_movies.head()

<ipython-input-18-2212af84fefc>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  user5_all_rated_movies=df[(df_ratings['userId']==5)]


movieId                                title  \
451      455                    Free Willy (1993)   
452      456                         Fresh (1994)   
453      457                 Fugitive, The (1993)   
454      458  Geronimo: An American Legend (1993)   
455      459                  Getaway, The (1994)   

                                            genres  
451                       Adventure|Children|Drama  
452                           Crime|Drama|Thriller  
453                                       Thriller  
454                                  Drama|Western  
455  Action|Adventure|Crime|Drama|Romance|Thriller

In [19]:
user5_all_rated_movies.shape

(66, 3)

In [21]:
len(user5_all_rated_movies.movieId.unique())

66

In [ ]:
#1.g. train recommender system using SVD object and predict the ratings for user id 5

In [ ]:
#1.h.print the top 10 movie recommendations for the user id 5